### PR TITLE
chore: Release

### PR DESCRIPTION
**Pull request by Dirreke**
## What's Changed
* Take proxy environment variables into account by @xoolive in https://github.com/blas-lapack-rs/openblas-src/pull/120
* rewrite CI by @gkobeaga and @Dirreke in https://github.com/blas-lapack-rs/openblas-src/pull/123
* Update OpenBLAS to version 0.3.28 by @Dirreke in https://github.com/blas-lapack-rs/openblas-src/pull/119
* Use pkg-config and fix build on doc.rs by @Fuuzetsu ,@j-baker and @HenrikJStromberg in https://github.com/blas-lapack-rs/openblas-src/pull/125
* Add cache for windows CI by @Dirreke in https://github.com/blas-lapack-rs/openblas-src/pull/128
Refactor code, Drop LAPACKE inspection, Drop FORTRAN check by @Dirreke in https://github.com/blas-lapack-rs/openblas-src/pull/127
* Detect TARGET, CC, HOSTCC, FC automically when cross-compiling by @Dirreke in https://github.com/blas-lapack-rs/openblas-src/pull/129
* Update README and CHANGELOGS by @Dirreke in  https://github.com/blas-lapack-rs/openblas-src/pull/130

## New Contributors
* @xoolive made their first contribution in https://github.com/blas-lapack-rs/openblas-src/pull/120

**Full Changelog**: https://github.com/blas-lapack-rs/openblas-src/compare/openblas-src-v0.10.9...openblas-src-v0.10.10

### CODE REVIEW

**Comment by Dirreke** [comment]
@termoshtt @IvanUkhov Hi, would you like to help merge it and release v0.10.10 to crates.io?

**Comment by IvanUkhov** [comment]
Thank you for all the work! I added you as an owner on crates.io. Feel free to publish.

**Comment by Dirreke** [comment]
Hi, I believe I also need permission for `openblas-build`. @termoshtt, could you kindly assist to publish it?

**Comment by IvanUkhov** [comment]
Hm, true. @termoshtt , please make us both additional owners.

**Comment by IvanUkhov** [comment]
OK, resolved. Toshiki was kind enough to add me, and now I have added you too, Dirreke. You should be able to publish.

**Pull request merged**
