### PR TITLE
homebrew directory depends on architecture. Include libomp libs

### PR DESCRIPTION
**Pull request by maparent**

### CODE REVIEW

**Comment by maparent** [comment]
Note: This allows a `cargo build -F system` on a M1 Mac. The build fails without system, I suspect for other reasons.

**Comment by maparent** [comment]
Note: Relevant to #54

**Comment by fahasch** [comment]
This is an important commit as more and more Mac systems are using ARM processors.

**Comment by termoshtt** [comment]
@maparent @fahasch 

Please could you test #93 works on ARM macOS machine? This uses `brew --prefix` command to get a path where brew install OpenBLAS.

**Comment by fahasch** [comment]
Works like a charm. Great job!

**Pull request merged**
